### ISSUE TITLE
[BE] 0414 TODO 

### ISSUE THREAD

**Issue by bong6981** [okstring/todo-list#24]
- [x] PR날린 것에 대한 수정 및 재리뷰 요청 
- [x] 배포 서버가 상시 동작 가능하게 한다 
- [x] iOS분들과 협의하여 API 재설계
